app = "fly-test-restart"
kill_signal = "SIGINT"
kill_timeout = 30
processes = []

# service with health check on port 8888
[[services]]
  internal_port = 8888
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http", "tls"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "10s"
    restart_limit = 0
    timeout = "2s"

[[restart]]
  policy = "always"
